/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Modelo.conectar;
import static Vistas.Principal.Compras;
import static Vistas.Principal.Bitacora;
import static Vistas.Principal.Parametros;
import static Vistas.Principal.Usuarios;
import static Vistas.Principal.p1;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    conectar cc=new conectar();
    Connection cn=cc.conexion();
    public Login() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    
    
    
   
    
    void acceder(String usus, String pass){ 
        String cap="";
        String sql="SELECT * FROM usuario WHERE nombre1_usuario='"+usus+"' && clave='"+pass+"'";
        try{ 
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            { 
              cap=rs.getString("tipo_usuario");
            }
            if(cap.equals("SuperUsuario"))
            { 
                
             Principal ko=new Principal();
             ko.setVisible(true);
             this.dispose();
             
             JOptionPane.showMessageDialog(this, "Bienvenido "+usus);
             p1.setText(usus);
             
            }
            
            if(cap.equals("Encargado(a)"))
            { 
              
             Principal koo=new Principal();
             koo.setVisible(true);
             this.dispose();
             Compras.setVisible(false);
             Bitacora.setVisible(false);
             Usuarios.setVisible(false);
             JOptionPane.showMessageDialog(this, "Bienvenido "+usus); 
             p1.setText(usus);
               
            }
            
            if(cap.equals("Vendedor(a)"))
            { 
              
             Principal koo=new Principal();
             koo.setVisible(true);
             this.dispose();
             Compras.setVisible(false);
             Bitacora.setVisible(false);
             Parametros.setVisible(false);
             Usuarios.setVisible(false);
             JOptionPane.showMessageDialog(this, "Bienvenido "+usus); 
             p1.setText(usus);
               
            }
            
           if((!cap.equals("SuperUsuario"))&&(!cap.equals("Encargado(a)"))&&(!cap.equals("Vendedor(a)"))) 
           { 
             JOptionPane.showMessageDialog(this, "Usted no esta Registrado");  
           }
        }
        
        catch(SQLException ex){ 
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        try{
            String descripcion="El usuario inicio sesion";
            PreparedStatement pst=cn.prepareStatement("INSERT INTO bitacora (usuario,descripcion,fecha,hora) VALUES (?,?,?,?)");           
            pst.setString(1, usus);
            pst.setString(2, descripcion);
            pst.setString(3, Principal.Fecha.getText());
            pst.setString(4, Principal.Hora2.getText());
            pst.executeUpdate();           
        }
        catch(SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contraseña1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 170, 280, 22);

        usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(usuario1);
        usuario1.setBounds(690, 160, 190, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 280, 280, 22);

        contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña1ActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña1);
        contraseña1.setBounds(690, 270, 190, 40);

        jButton2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton2.setText("ACCEDER");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(255, 0, 0)));
        jButton2.setPreferredSize(new java.awt.Dimension(250, 150));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 380, 330, 130);

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 130, 590, 380);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(360, 110, 640, 420);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.JPG"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(-20, -170, 1420, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario1ActionPerformed

    private void contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseña1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String usu=usuario1.getText();
        String pas=new String(contraseña1.getPassword());

        acceder(usu, pas);

        /* if(usuario1.getText().equals(Usuario2)&&Contra.equals(Contraseña2)) {

            Entrada2 c=new Entrada2();
            c.setVisible(true);
            dispose();

        }
        else {
            JOptionPane.showMessageDialog(this, "INVALIDO");
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JPasswordField contraseña1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
