/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.conectar;
import Validaciones.TextFieldEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static org.apache.poi.hssf.usermodel.HeaderFooter.tab;


import Validaciones.TextFieldEvent;

import Modelo.Compras2;
import static Vistas.Principal.p1;
import java.awt.Color;
import java.util.List;

public class Parametros extends javax.swing.JInternalFrame {

    conectar cc=new conectar();
    Connection cn=cc.conexion();


    
    TextFieldEvent evento= new TextFieldEvent();

    public Parametros() {
        initComponents();
        encargado.setText(p1.getText());
        encargado.setEnabled(false);
        encargado.setVisible(false);
        parametros();
        
    }
  
    void parametros(){ 
             String sql="";
        sql="select * from parametros_adicionales where id_parametros_adicionales=1";
        try {
        java.sql.Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        if(rs.first()){
            iva.setText(rs.getString("porcentaje_iva_v"));
            descuento.setText(rs.getString("porcentaje_descuento"));
            dolar.setText(rs.getString("dolar"));
        }
        }
        catch(SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al realizar la consulta");
        
         }}
    
    
         void calcular()
    {
        double preciox=0;
        int cantidadx=0;  
        double subtotalx=0;
        double ivax=0;
        double descuentox=0;
        double totalx=0;
        
        String ivaxx;
        String descuentoxx;
        
        ivaxx=iva.getText();
        ivax=Double.parseDouble(ivaxx);
        descuentoxx=descuento.getText();
        descuentox=Double.parseDouble(descuentoxx);
       
        subtotalx=preciox*cantidadx;
        ivax=(ivax*subtotalx)/100;
        descuentox=(descuentox*subtotalx)/100;
        totalx=subtotalx-(ivax+descuentox);     
    }
         
         
         void bitacora(){ 
        try{
            String descripcion="Modifico los parametros adicionales";
            PreparedStatement pst=cn.prepareStatement("INSERT INTO bitacora (usuario,descripcion,fecha,hora) VALUES (?,?,?,?)");           
            pst.setString(1, encargado.getText());
            pst.setString(2, descripcion);
            pst.setString(3, Principal.Fecha.getText());
            pst.setString(4, Principal.Hora.getText());
            pst.executeUpdate();           
        }
        catch(SQLException ex){
            Logger.getLogger(Parametros.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }
         
         
         
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dolar = new javax.swing.JTextField();
        encargado = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insertar.png"))); // NOI18N
        jButton11.setText("Guardar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(170, 330, 190, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("IVA");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(90, 70, 120, 30);

        iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ivaKeyTyped(evt);
            }
        });
        jPanel2.add(iva);
        iva.setBounds(260, 70, 150, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("Descuento");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(90, 140, 120, 30);

        descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descuentoKeyTyped(evt);
            }
        });
        jPanel2.add(descuento);
        descuento.setBounds(260, 140, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Parametros Adicionales");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 20, 290, 29);
        jPanel2.add(ID);
        ID.setBounds(800, 310, 100, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setText("Valor del dolar");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 220, 150, 30);

        dolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dolarKeyTyped(evt);
            }
        });
        jPanel2.add(dolar);
        dolar.setBounds(260, 220, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 310);

        encargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encargadoActionPerformed(evt);
            }
        });
        getContentPane().add(encargado);
        encargado.setBounds(230, 410, 70, 30);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.JPG"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, 0, 1420, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try{
            PreparedStatement pst=cn.prepareStatement("UPDATE parametros_adicionales "
                + "SET porcentaje_iva_v='"+iva.getText()
                +"',porcentaje_descuento='"+descuento.getText()
                +"',dolar='"+dolar.getText()
                +"' WHERE id_parametros_adicionales=1"             
            );
            pst.executeUpdate();
           bitacora();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                               
   
    }//GEN-LAST:event_jButton11ActionPerformed

    private void ivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaKeyTyped
       evento.numberKeyPress(evt);
    }//GEN-LAST:event_ivaKeyTyped

    private void descuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyTyped
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_descuentoKeyTyped

    private void encargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encargadoActionPerformed

    private void dolarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dolarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dolarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField dolar;
    private javax.swing.JTextField encargado;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
